config/routes.rb
Rails.application.routes.draw do

  resources :bands
  resources :bands
  resources :venues
  root 'static_pages#home'

  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'readme'  => 'static_pages#readme'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  resources :genres
  resources :users
  

end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:index, :show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @bands = Band.where(genre_id: @genre.id).find_each
    @users = User.where(genre_id: @genre.id).find_each
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if Genre.find_by(title: genre_params[:title]) == nil
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
      else
        updateAlert = "<div class=\"alert alert-danger alert-dismissable\"><strong>Failed to create genre:</strong> It already exists bro<button type=\"button\" data-dismiss=\"alert\" class=\"close\"><span>&times;</span></button></div>"
        format.html { redirect_to @genre, notice: updateAlert  }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:title)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Information</legend>
    <div class="form-group">
      <div class="field">
	<%= f.label :title, "Title:", class: "form-control-label" %><br>
	<%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Create Genre', :class => 'btn btn-success' %>
    </div>
  </fieldset>
<% end %>

app/views/genres/edit.html.erb
<div class="page-header">
  <h1>Editing Genre</h1>
</div>

<%= render 'form' %>

<%= link_to '<button class="btn btn-info">Show</button>'.html_safe, @genre %>
<%= link_to '<button class="btn btn-default">Back</button>'.html_safe, genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice.html_safe if notice %></p>

<div class="page-header">
  <h1>Genres <small>a bunch of different kinds</small></h1>
</div>

<table class="table table-nonfluid">
  <thead>
    <tr>
      <th class="text-left fixed-width-col">Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.title %></td>
        <td><%= link_to '<button class="btn btn-info">Show</button>'.html_safe, genre %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button class="btn btn-success">New Genre</button>'.html_safe, new_genre_path %>

app/views/genres/new.html.erb
<div class="page-header">
  <h1>New Genre</h1>
</div>

<%= render 'form' %>

<br>

<%= link_to '<button class="btn btn-default">Back</button>'.html_safe, genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice.html_safe if notice %></p>

<div class="page-header">
  <h1>Genre <small></small></h1>
</div>

<ul class="list-group">
  <li class="list-group-item"><h4>Title: <small><%= @genre.title %></small></h4>
</ul>
<table class="table">
  <thead>
    <tr>
      <th class="text-left">Venue rating</th>
      <th class="text-center">User rating</th>
      <th class="text-left">Name</th>
      <th class="text-center">Selfie</th>
      <th class="text-left">Genre</th>
      <th class="text-left">Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td class="text-left"><%= band.venue_rating %></td>
        <td class="text-center"><%= band.user_rating %></td>
        <td class="text-left"><%= band.name %></td>
        <td class="text-center"><%= selfieMarkup(band) %></td>
        <td class="text-left"><%= band.genre.title if band.genre %></td>
        <td class="text-left"><%= band.user.name %></td>
        <td><%= link_to '<button class="btn btn-info">Show</button>'.html_safe, band %></td>
        <% if current_user.id == band.user_id %>
          <td><%= link_to '<button class="btn btn-warning">Edit</button>'.html_safe, edit_band_path(band) %></td>
          <td><%= link_to '<button class="btn btn-danger">Destroy</button>'.html_safe, band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '<button class="btn btn-default">Back</button>'.html_safe, genres_path %>