config/routes.rb
Rails.application.routes.draw do

  resources :bands
  resources :bands
  resources :venues
  root 'static_pages#home'

  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'readme'  => 'static_pages#readme'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  resources :genres
  resources :users
  

end

app/models/band.rb
class Band < ActiveRecord::Base
  belongs_to :genre
  belongs_to :members
  belongs_to :user
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  require 'html_helper'
  require 'users_helper'

  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    createAlert = "<div class=\"alert alert-success alert-dismissable\"><strong>Band Created!</strong> You successfully added a band. <button type=\"button\" data-dismiss=\"alert\" class=\"close\"><span>&times;</span></button></div>"
    @band = Band.new(band_params)
    @band.venue_rating = 0
    @band.user_rating = 0
    @band.venue_rating_count = 0
    @band.user_rating_count = 0

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: createAlert }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    updateAlert = "<div class=\"alert alert-success alert-dismissable\"><strong>Band Updated!</strong> You successfully updated a band. <button type=\"button\" data-dismiss=\"alert\" class=\"close\"><span>&times;</span></button></div>"
    respond_to do |format|
      if(band_params[:user_rating])
        @band.user_rating_count = @band.user_rating_count + 1
        @band.user_rating = (@band.user_rating * (@band.user_rating_count-1) + band_params[:user_rating].to_f)/@band.user_rating_count
        updateAlert = "<div class=\"alert alert-success alert-dismissable\"><strong>Thanks for the rating</strong><button type=\"button\" data-dismiss=\"alert\" class=\"close\"><span>&times;</span></button></div>"
        if @band.update :user_rating => @band.user_rating, :user_rating_count => @band.user_rating_count
          format.html { redirect_to @band, notice: updateAlert }
          format.json { render :show, status: :ok, location: @venue }
        else
          format.html { render :edit }
          format.json { render json: @band.errors, status: :unprocessable_entity }
        end
      elsif(band_params[:venue_rating])
        @band.venue_rating_count = @band.venue_rating_count + 1
        @band.venue_rating = (@band.venue_rating * (@band.venue_rating_count-1) + band_params[:venue_rating].to_f)/@band.venue_rating_count
        updateAlert = "<div class=\"alert alert-success alert-dismissable\"><strong>Thanks for the rating</strong><button type=\"button\" data-dismiss=\"alert\" class=\"close\"><span>&times;</span></button></div>"
        if @band.update :venue_rating => @band.venue_rating, :venue_rating_count => @band.venue_rating_count
          format.html { redirect_to @band, notice: updateAlert }
          format.json { render :show, status: :ok, location: @band }
        else
          format.html { render :edit }
          format.json { render json: @band.errors, status: :unprocessable_entity }
        end
      elsif current_user.id == @band.user_id
        if @band.update(band_params)
          format.html { redirect_to @band, notice: updateAlert }
          format.json { render :show, status: :ok, location: @band }
        else
          format.html { render :edit }
          format.json { render json: @band.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
        if current_user.id == @band.user_id

    destroyAlert = "<div class=\"alert alert-success alert-dismissable\"><strong>Band Destroyed!</strong> You successfully destroyed a band. <button type=\"button\" data-dismiss=\"alert\" class=\"close\"><span>&times;</span></button></div>"
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: destroyAlert }
      format.json { head :no_content }
    end
    else
      updateAlert = "<div class=\"alert alert-danger alert-dismissable\"><strong>Failed to update:</strong> You don't own this band<button type=\"button\" data-dismiss=\"alert\" class=\"close\"><span>&times;</span></button></div>"
      format.html { redirect_to @band, notice: updateAlert  }
      format.json { render json: @band.errors, status: :unprocessable_entity }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_band
    @band = Band.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def band_params
    params.require(:band).permit(:venue_rating, :user_rating, :name, :selfie, :genre_id, :user_id)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
<legend>Information</legend>
<div class="field-group">
  <div class="field">
    <%= f.label :name, "Name", class: "form-control-label" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :selfie, "Selfie", class: "form-control-label" %><br>
    <%= f.url_field :selfie, class: "form-control" %>
  </div>
  <div class="select">
    <%= f.label :genre_id, "Genre", class: "form-control-label" %><br>
    <%= f.collection_select :genre_id, Genre.order(:title),:id,:title, {:class=> "form-control"} %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
</div>
<br>
  <div class="actions">
    <%= f.submit 'Create Band', :class=> 'btn btn-success' %>
  </div>
</fieldset>
<% end %>

app/views/bands/_user.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>%
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_rating, "How much do you like #{@band.name}:", class: "form-control-label" %><br>
    <%= f.number_field :user_rating, in: 1...6, class: "form-control" %>
    <%= f.hidden_field :user_id, :value => current_user.id %> <br>
    <%= f.submit 'Submit Quality Rating', :class=> 'btn btn-success' %>
  </div>  
<% end %>

app/views/bands/_venue.html.erb
<% if is_venue_owner? %>
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>%
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :venue_rating, "Venue Rating:", class: "form-control-label" %><br>
    <%= f.number_field :venue_rating, in: 1...6, class: "form-control" %>
    <%= f.hidden_field :user_id, :value => current_user.id %> <br>
    <%= f.submit 'Submit Price Rating', :class=> 'btn btn-success' %>
  </div>  
<% end %>
<% end %>

app/views/bands/edit.html.erb
<div class="page-header">
  <h1>Editing Band</h1>
</div>

<%= render 'form' %>

<%= link_to '<button class="btn btn-info">Show</button>'.html_safe, @band %>
<%= link_to '<button class="btn btn-default">Back</button>'.html_safe, bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice.html_safe if notice %></p>

<div class="page-header">
  <h1>Bands <small>every group you know and love</small></h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th class="text-left">Venue rating</th>
      <th class="text-left">User rating</th>
      <th class="text-left">Name</th>
      <th class="text-center">Selfie</th>
      <th class="text-left">Genre</th>
      <th class="text-left">Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% if @bands != nil %>
    <% @bands.each do |band| %>
      <tr>
        <td class="text-left"><span class="stars"><%= band.venue_rating %></span></td>
        <td class="text-left"><span class="stars"><%= band.user_rating %></span></td>
        <td class="text-left"><%= band.name %></td>
        <td class="text-center"><%= selfieMarkup(band) %></td>
        <td class="text-left"><%= band.genre.title if band.genre %></td>
        <td class="text-left"><%= band.user.name %></td>
        <td><%= link_to '<button class="btn btn-info">Show</button>'.html_safe, band %></td>
        <% if current_user.id == band.user_id %>
          <td><%= link_to '<button class="btn btn-warning">Edit</button>'.html_safe, edit_band_path(band) %></td>
          <td><%= link_to '<button class="btn btn-danger">Destroy</button>'.html_safe, band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      	<% else %>
	  <td></td>
	  <td></td>
	<% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button class="btn btn-success">New Band</button>'.html_safe, new_band_path %>

app/views/bands/new.html.erb
<div class="page-header">
  <h1>New Band</h1>
</div>

<%= render 'form' %>

<%= link_to '<button class="btn btn-info">Back</button>'.html_safe, bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice.html_safe if notice %></p>

<div class="page-header">
  <h1>Band Info <small>these guys rock</small></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="jumbotron text-center">
      <%= selfieMarkup(@band) %><br> 
      <%= render 'user' %>
      <%= render 'venue' %>  <br>
    </div>
  </div>
  <div class="col-md-8">
    <div class="list-group">
      <li class="list-group-item"><h4>Name: <small><%= @band.name %></small></h4></li>
      <li class="list-group-item"><h4>Genre: <small><%= @band.genre.title %></small></h4></li>
      <li class="list-group-item"><h4>User Rating:</h4><span class="stars"><%= @band.user_rating %></span></li>
      <li class="list-group-item"><h4>Venue Rating:</h4><span class="stars"><%= @band.venue_rating %></span></li>
      <li class="list-group-item"><h4>Owner: <small><%= link_to @band.user.name, @band.user %></small></h4></li>
    </div>
  </div>
</div>

<% if current_user.id == @band.user_id %>
  <%= link_to '<button class="btn btn-info">Edit</button>'.html_safe, edit_band_path(@band) %>
<% end %>
<%= link_to '<button class="btn btn-default">Back</button>'.html_safe, bands_path %>