config/routes.rb
Rails.application.routes.draw do

  resources :bands
  resources :bands
  resources :venues
  root 'static_pages#home'

  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'readme'  => 'static_pages#readme'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  resources :genres
  resources :users
  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navbar.html.erb
    <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="\
collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Venue Share</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <% if logged_in?%>
              	<li><%= link_to 'My Info', current_user%></li>
              	<li><%= link_to 'Venues', venues_path%></li>
              	<li><%= link_to 'Bands', bands_path%></li>
              	<li><%= link_to 'Genres', genres_path%></li>
              	<li><%= link_to 'Users', users_path%></li>
              	</ul>
              	<ul class="nav navbar-nav navbar-right">
              	<li><%= link_to 'Logout', logout_url, :method => :delete %></li>
              	<li><%= link_to 'About', about_url %></li>
              	<li><%= link_to 'Contact', contact_url %></li>
              	<li><%= link_to 'README', readme_url %></li>
              	</ul>
              <% else %>
              	<li class="active"><a href="../../../../../">Home</a></li>
              	</ul>
              	<ul class="nav navbar-nav navbar-right">
              	<li><%= link_to 'Login', login_url %></li>
              	<li><%= link_to 'About', about_url %></li>
              	<li><%= link_to 'Contact', contact_url %></li>
              	<li><%= link_to 'README', readme_url %></li>
              	</ul>
              <% end%>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VenueShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>	
  <%= render "/layouts/navbar" %>
  <div class="container">    
    <%= yield %>
  </div>
</body>
</html>